### PR TITLE
Added Nicehash GPU mining tab (WIP) (Quick Design)

### PR DESCRIPTION
**Pull request by danielkp1234**
@UnamSanctam I started on the integration of Nicehash GPU mining. That would increase profits for GPU mining. There are probably some errors here since I don't really have a lot of experience with vb.net I mostly do java.
Currently, the tab is more or less complete and the parameters for NB-miner has been stored as a string. The worker name and BTC Adresse/Nicehash miner address still need to be changed and NB-miner still needs to be integrated.

### CODE REVIEW

**Comment by knw1501** [comment]
получается сейчас еще незьзя майнить через nicehash с помощью GPU ни одну валюту? и можно ли будет сделать для GPU такой же таймер (idle Mining) который работает с CPU?

**Comment by danielkp1234** [comment]
@knw1501 I used google translate so sorry if I don't understand. But yes I am pretty sure idle mining should be supported.
If not I think we are gonna have to use something other than NB-miner.
This miner made by Nicehash is also pretty much neck in neck with NB-miner 
and its open-source
https://github.com/nicehash/excavator

**Comment by UnamSanctam** [comment]
I am currently working on a custom version of https://github.com/ethereum-mining/ethminer at the moment and have gotten most of it done. Through all my tests NBMiner and Ethminer mine at the same hashrate for me so it should work well.

**Comment by danielkp1234** [comment]
@UnamSanctam Very cool, Will NiceHash be supported? with something like a custom stratum?
https://www.nicehash.com/stratum-generator

**Comment by UnamSanctam** [comment]
Well, ethminer natively supports NiceHash so you just have to use it normally.

**Comment by danielkp1234** [comment]
@UnamSanctam Yeah I know, but changing the params of ethminer stills needs to possible from the builder settings. btw are you planning on integrating ethminer into this project or make a new one focused on ethereum?

**Comment by UnamSanctam** [comment]
Yeah but you can use the default settings for NiceHash. there's no extra options to enter (automatic stratum2). I am not sure whether to integrate it or not, only problem is that the current name is Silent XMR Miner.

**Comment by danielkp1234** [comment]
@UnamSanctam Yeah, I probably could do that I didn't know about the default settings. And you could just change the project name and integrate it. Since XMR is probably best for CPU and ethereum is great for GPU it would be a good combined solution.

**Comment by danielkp1234** [comment]
Just saw that my PR contains multiple issues in the Form Design

**Pull request closed without merging**
