### PR TITLE
Automatic removal date feature

### PR DESCRIPTION
**Pull request by danielkp1234**
@UnamSanctam I have implemented the GUI part of allowing the set of an automatic removal date.
image

It currently gives the builder a #RemovalDate containing the date from the date selector.
But I couldn't figure out how to debug the program.vb that is being built by the main Form.

I also added a reference (assuming it works) to the removal date in Program.vb and a reference to Today's date.

My idea is it would run a check on the startup of the program and every 24 hours to check if the removal date has passed and then delete the file from %temp% and remove the registry entry

### CODE REVIEW

**Comment by danielkp1234** [comment]
@UnamSanctam How is it going with working on the custom ethminer and integration into the program?

**Comment by UnamSanctam** [comment]
Well it is mostly done but there are still inherent problems with GPU mining that I have to solve. First is that GPU takes all or nothing, you can't really use 20%, 40% or 80% but must always use 100% of the required usage since that is how GPU mining works. Second of all is that the Ethereum DAG takes 4.17GB of VRAM currently so only cards with 6-8GB of can run it, meaning that most users can't run it.

**Comment by danielkp1234** [comment]
@UnamSanctam Yeah, but you can't really do a lot about the DAG size but arent most GPUs 6gb+?

**Comment by danielkp1234** [comment]
@UnamSanctam Hey I just implemented more of the checks in Program.vb the only thing needed now before a merge would be a timer to check if the removal date has passed every 24 hours. and the self-destruct function to remove registry entry and file from savepath. On line 128 the removal should begin. :)

**Comment by danielkp1234** [comment]
@UnamSanctam How is it going with the update? :)

**Comment by danielkp1234** [comment]
btw isn't GPU mining actually more hidden than CPU mining if you look at for example task manager it doesn't show any GPU usage from the mining since (at least in my case) it only by default shows the 3d GPU usage and not the Cuda cores usage

**Comment by danielkp1234** [comment]
I have also recently tried to get the theme matching for the DateTimePicker I tried to make a Custom DateTimePicker that inherits the default DateTimePicker and overwrite the foreground colour and the background color to a black colour but that didn't work

**Comment by UnamSanctam** [comment]
Yes it is usually more undetectable for that reason. The problem with GPU mining is that you can't really use anything less that 100% of the required VRAM so you can't run any VRAM expensive things in the meanwhile.

Getting custom theme functions can take a bit of tinkering and mostly undocumented knowledge.

But for the update I'm probably going to make the ETH miner in a separate builder and if someone wants to mine XMR on the CPU and ETH on the GPU it would be better to use a file binder on the two compiled miners.

**Comment by danielkp1234** [comment]
@UnamSanctam Okay nice, IMO I think it doesn't really matter that much if it can be set to only idle mine. btw could you be interested in merging this PR/making something similar?

**Comment by UnamSanctam** [comment]
That's what I was thinking but for idle mining to work I need to find a way to free the allocated memory when active and then reallocate it safely and efficiently when idle.

And yes I can make something similar, the PR lacks a few things needed for it to be implemented.

**Comment by danielkp1234** [comment]
@UnamSanctam Not to sound annoying but when will you be creating a new repo for the ETH miner. I am looking forward to it :)

**Comment by danielkp1234** [comment]
Hey, you were talking about how to free allocated memory when not idle. Here its looks like you can just "pause" ethminer

https://github.com/ethereum-mining/ethminer/blob/master/docs/API_DOCUMENTATION.md#miner_pausegpu

**Comment by UnamSanctam** [comment]
Yes but from my tests and looking at the code it does not free the allocated VRAM.

**Comment by danielkp1234** [comment]
Weird, I thought it would clear allocated VRAM, but it does stop the usage of the cuda cores right?

**Comment by UnamSanctam** [comment]
I believe so.

**Comment by danielkp1234** [comment]
Well if you cant pause ethminer to free VRAM can't you just make ethminer close when the pc is no longer idle and make it start again when it's idle even tho its a more inefficient way to do it :)

**Comment by UnamSanctam** [comment]
No since my miner builder/injector closes down after injecting so that it's harder to find it.

**Comment by danielkp1234** [comment]
Oh, yeah that's right. So the major problem is freeing the VRAM right?. You could always do an alpha release without the VRAM freeing as a starting point.

**Comment by danielkp1234** [comment]
Or you could do a post on the ethminer repo and ask

**Comment by danielkp1234** [comment]
@UnamSanctam Would it be an option in the initial alpha release to not include the freeing of the VRAM until you have solved how to do it. You could always ask on the ethminer repo :)

**Comment by UnamSanctam** [comment]
Well if it doesn't free the VRAM you can't really do any GPU intensive tasks while it's idle but I should be able to solve the freeing of the allocated VRAM, it only takes time since I have to run a lot of tests.

**Comment by danielkp1234** [comment]
Awesome!, I can help test an alpha version if needed :)

**Comment by jeric64** [comment]
I tried to test the latest version of the miner on a virtual server. Poole chose minergate. I set everything up, did build. But at startup, the application is launched with the name I invented for it, and not with the process that I specified in build. The process just hangs, there is no load, mining is not going on.

**Comment by UnamSanctam** [comment]
Well you should probably make your own issue but did you wait the amount of time you chose in 'Start Delay'? It will run as the application it started as for that amount of time to avoid scantime detections. (Although if you have "Install" enabled it will already have copied the files and started the watchdog so that it will still work even if the process is closed.)

**Comment by jeric64** [comment]
Do you have a jabber?

**Comment by UnamSanctam** [comment]
No I don't, but if you wait the amount set in 'Start Delay' does it not start the program name you chose in the 'Install' tab then (and then injects into whatever program you chose, by default explorer.exe)?

**Comment by golxd** [comment]
1. idle mining works for both cpu and gpu?
2. when launching ready miner, windows defender reacts, is this the norm?

**Comment by UnamSanctam** [comment]
The uninstaller is good enough for the use cases this would be used for.

**Pull request closed without merging**
